== Elasticsearch GORM plugin

An Elasticsearch plugin for Grails; This project is a fork based on the great work done by the guys at https://github.com/mstein/elasticsearch-grails-plugin.

=== Why would you want to fork the original Elasticsearch plugin?

The original Elasticsearch plugin relies on *Hibernate-specific* GORM components, thus rendering it unusable if you back your Grails application by any other database.

=== How can I obtain the plugin?

The plugin is still in beta, so it hasn't been officially released to Grails' plugin center. +
In the meantime you can install the plugin in one of two ways:

==== 1. Inline

Clone this repository and add an inline plugin dependency to your project's +BuildConfig.groovy+ file:

----
grails.plugin.location.'elasticsearch-gorm-grails-plugin' = '/path/to/cloned/repo'
----

==== 2. Binary Dependency

Snapshot versions of the plugin are deployed to a repository at http://noams.artifactoryonline.com. +
You can resolve the snapshot version by editting your project's +BuildConfig.groovy+ file, by adding the plugins' snapshot repository and a standard snasphot dependency declaration:

----
grails.project.dependency.resolution = {
    repositories {
        mavenRepo 'http://noams.artifactoryonline.com/noams/grails-elasticsearch-plugin-snapshots/'
    }
    plugins {
        compile ':elasticsearch-gorm:0.0.1-SNAPSHOT'
    }
}
----

== License

----
Copyright 2013 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----




==== Here, have a yak:
----
                            _,,,_
                        .-'`  (  '.
                     .-'    ,_  ;  \___      _,
                 __.'    )   \'.__.'(:;'.__.'/
         __..--""       (     '.__{':');}__.'
       .'         (    ;    (   .-|` '  |-.
      /    (       )     )      '-p     q-'
     (    ;     ;          ;    ; |.---.|
     ) (              (      ;    \ o  o)
     |  )     ;       |    )    ) /'.__/
     )    ;  )    ;   | ;       //
     ( )             _,\    ;  //
     ; ( ,_,,-~""~`""   \ (   //
      \_.'\\_            '.  /<_
       \\_)--\             \ \--\
   jgs )--\""`             )--\"`
       `""`                `""`
----
